import { RootLayout } from "@/components/layout/RootLayout";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function PrivacyPage() {
  return (
    <RootLayout>
      <section className="container py-12">
        <div className="mx-auto max-w-3xl space-y-8">
          <Link
            href="/"
            className="flex items-center text-sm text-muted-foreground hover:text-foreground"
          >
            <ArrowLeft className="mr-1 h-4 w-4" />
            Back to home
          </Link>

          <div>
            <h1 className="mb-6 text-3xl font-bold">Privacy Policy</h1>

            <div className="prose prose-zinc dark:prose-invert max-w-none">
              <p>Last updated: May 22, 2025</p>

              <h2>Introduction</h2>
              <p>
                GovBot (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;)
                respects your privacy and is committed to protecting it through
                our compliance with this policy. This policy describes the types
                of information we may collect from you or that you may provide
                when you use our GovBot service.
              </p>

              <h2>Information We Collect</h2>
              <p>When you interact with GovBot, we collect:</p>
              <ul>
                <li>
                  Chat messages sent to GovBot during proposal discussions
                </li>
                <li>Proposal information from Polkassembly</li>
                <li>Voting decisions and reasoning generated by GovBot</li>
              </ul>

              <h2>How We Use Your Information</h2>
              <p>
                We use information that we collect about you or that you provide
                to us:
              </p>
              <ul>
                <li>To provide you with our GovBot service</li>
                <li>
                  To generate appropriate AI responses based on your inputs
                </li>
                <li>To maintain and improve our service</li>
                <li>To provide public governance decisions and explanations</li>
              </ul>

              <h2>Data Retention</h2>
              <p>
                We retain chat data, proposal information, and voting decisions
                to maintain context and history for the governance process. This
                information may be publicly visible on Polkassembly.
              </p>

              <h2>Public Nature of Governance</h2>
              <p>
                Please be aware that interactions with GovBot related to
                governance proposals are intended to be public. Voting decisions
                and reasoning will be posted publicly on Polkassembly.
              </p>

              <h2>Changes to Our Privacy Policy</h2>
              <p>
                We may update our privacy policy from time to time. We will post
                any changes on this page and update the &quot;Last updated&quot;
                date.
              </p>

              <h2>Contact Information</h2>
              <p>
                If you have any questions or comments about this privacy policy,
                please contact us at [contact email/information].
              </p>
            </div>
          </div>
        </div>
      </section>
    </RootLayout>
  );
}
